name:                db-schema
version:             0.1.0.0
github:              "odr/db-schema"
license:             BSD3
author:              "Dmitry Olshansky"
maintainer:          "olshanskydr@gmail.com"
copyright:           "Dmitry Olshansky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            web, type, database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/odr/db-schema#readme>

dependencies:
- base >= 4.7 && < 5
- singletons
- template-haskell
- text
- exceptions
- transformers
- text-format
- ghc-prim
- bytestring
- direct-sqlite
- time


library:
  source-dirs: src

executables:
  db-schema-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-schema

tests:
  db-schema-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-schema
